non_product_codes:
- CEM-2004
- CEM2004
- EN-50
- EN-54
- EN50
- EN54
- GRANDI-22
- IP-65
- IP-66
- IP-67
- IP-68
- IP65
- IP66
- IP67
- IP68
- ISO-14001
- ISO-9001
- ISO14001
- ISO9001
- MM-95
- NFPA-72
- NFPA72
- UL-268
- UL268
- ULTRA-123
generic_model_regex: \b([A-Z]{2,6})[-\s]?(\d{2,4})([A-Z]?(?:-\d{1,3})?)\b
