manufacturer: Notifier
distributor: null
filename_patterns:
- \b(B5\d{2}[A-Z]{0,4})\b
letter_models:
- PEARL
- INSPIRE
- AgileIQ
model_prefixes:
- AFP
- AM
- ID
- IDX
- NFS
- NFG
- NFXI
- NFX
- RP
- FAAST
- MIDT
- MPDT
- MNDT
- MADT
- MCDT
